cache:
  directories:
    - $HOME/.jmeter/
dist: xenial
jdk: oraclejdk8
jobs:
  include:
    -
      install:
        - "sudo -H pip install -q -I bzt"
        - "sudo -H pip install --upgrade six"

      script:
        - "mvn clean install -q"
        - "cd target/jmeter-test"
        - "travis_wait sudo sh testJmeterTravis.sh '3.3'"
        - "travis_wait sudo sh testJmeterTravis.sh '4.0'"
        - "travis_wait sudo sh testJmeterTravis.sh '5.0'"
        - "travis_wait sudo sh testJmeterTravis.sh '5.1'"
        - "travis_wait sudo sh testJmeterTravis.sh '5.1.1'"
        - "travis_wait sudo sh testJmeterTravis.sh '5.0' ${BZ_TOKEN}"
      stage: "JMeter Compatibility"

      before_deploy:
        - "mvn --batch-mode versions:set -DnewVersion=$(T=${TRAVIS_TAG%%-lib}; echo ${T:1})"
      deploy:
        api_key: "${GH_TOKEN}"
        file_glob: true
        provider: releases
        skip_cleanup: true
        file: target/jmeter-bzm-hls-*.jar
        name: "HLSPlugin"
        on:
          repo: Blazemeter/HLSPlugin
          tags: true
      script:
        - "mvn clean install -q -DskipTests"
      stage: "GitHub Release"
language: python
